import "./globals.css";
import { inter_tight, poppins, manrope } from "./fonts.js";

export const metadata = {
  title: "Elara AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`bg-black ${inter_tight.variable} ${poppins.variable} ${manrope.variable}`}
    >
      <body className=" antialiased">{children}</body>
    </html>
  );
}
